### PR TITLE
Optimizations, Toolchain separations, and cleanup.

### PR DESCRIPTION
**Pull request by frap129**
Gonna keep it short and simple. The commits here:
- Add a bunch of optimizations (if ELECTRIFY=true is either exported or added to ~/.bashrc)
- Add Graphite loop optimizations (if SaberMod toolchain is detected)
- Separate deffinitions for arm-eabi and androideabi toolchains
- Cleanup armv7-a-neon.mk
- Cleanup dumpvar.mk
- Cleanup emulator.mk

### CODE REVIEW

**Comment by iceandfire** [comment]
Are these OS X compatible?

**Comment by frap129** [comment]
I'm not sure if sabermod is, but anything that relies on SaberMod (graphite) automatically detects if I sabermod toolchain is being used, and won't enable if it isn't. So in short, everything that isn't compatable automatically disables so it works.

**Comment by frap129** [comment]
Just checked, and natively SaberMod toolchains dont support OSX, but I'm compiling an OSX compatible version right now!

**Comment by frap129** [comment]
Well, turns out you need to actually be running OSX to build it, but if you want to build it its not that hard.

**Comment by pbeeler** [comment]
Any luck compiling for osx?

**Comment by iceandfire** [comment]
@pbeeler none. :(

**Pull request merged**
